### ISSUE TITLE
NoSuchFileException exception when start from RAM-Disk

### ISSUE THREAD

**Issue by aFooBar** [xpipe-io/xpipe#118]
Hi,
When trying to start XPipe deamon, it raise following error message: "java.nio.file.NoSuchFileException: R:\**Device\ImDisk0\**XPipe\app\xpiped.exe"

The problem that 'Device\ImDisk0\' is added to the real path; thus lead to an invalid path.
I'm using ImDisk RAM-Disk that is mounted to R:\ on my Windows 23H2 PC.

I don't know if the problem comes from your application or from Java; but I was about trashing your application, before giving it a chance to show it's usefulness.

At the moment, I've only tested it with my Raspberry; but it looks promising 👍

**Comment by crschnick** [comment]
Someone else reported a similar issue yesterday via the built-in issue reporter so I already investigated. I honestly did not account for this case here until now: https://github.com/xpipe-io/xpipe/commit/741edbec0df6f7dca141f4b3f5b51781b1f48a9b because I did not expect https://docs.oracle.com/javase/8/docs/api/java/nio/file/Path.html#toRealPath-java.nio.file.LinkOption...- to fail in this case.

You can try whether the PTB build works for you: https://github.com/xpipe-io/xpipe-ptb/releases/tag/1.7.12-2

If not, I guess I have to set up ImDisk by myself to see what's wrong and try to find a solution.

**Comment by crschnick** [comment]
By the way, is there any particular reason why you are using a ramdisk? Always helps me to understand how people are using xpipe in practice

**Comment by aFooBar** [comment]
Hi Christopher,

I'm using RAMdisk for my Temp and testing / trash folder.
I'm using RAMdisk for speed, to spare write cycles on my SSDs and, also the fact it is flushed when I reboot my PC.

So I put the portable build to test your application to see if it is useful, meet my needs before installing it on my main drive.

I fully understand, that having such report is odd; how the hell would someone install/use an application on RAMdisk 🤔

I'll look at your second email and test your app further when I got some spare time and needs to connect to my Raspberry and my NASes.

Thanks for your application, for providing it to the community.

Regards,
F.B


Le 23 décembre 2023 20:51:51 GMT+01:00, Christopher Schnick ***@***.***> a écrit :
>By the way, is there any particular reason why you are using a ramdisk? Always helps me to understand how people are using xpipe in practice
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/xpipe-io/xpipe/issues/118#issuecomment-1868359786
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>
-- 
Envoyé de mon appareil Android avec Courriel K-9 Mail. Veuillez excuser ma brièveté.

**Comment by crschnick** [comment]
So this probable fix is now released. I'm interested whether it will actually work, maybe it will fail later down the line where I forgot something else.

**Comment by crschnick** [comment]
Great, so we can close this now
