### ISSUE TITLE
How to change ssh client to e.g. tabby under windows 11 to get rid of  the "too open keyfiles"

### ISSUE THREAD

**Issue by 001oc** [xpipe-io/xpipe#130]
Hi,

I would like to give x-pipe a try but stuck at the very beginning. I have difficulties to get ssh running under windows 11 with the built in ssh client ( I never use elsewhere). It (the annoying built in ssh client of windows) is complaining about "too open key files". I would like to change the by x-pipe used ssh client to e.g. tabby or at least putty or something else to get rid of such bullshit bingo with "too open key files". I am not willing to fight my way down to a "not too open key file" by changing the file permissions. My key files are good as they are :-). How is it done in x-pipe to force it to use another ssh client of my choice.

Thanks alot for your help

Michael

**Comment by crschnick** [comment]
Yeah the key file permissions and Windows with OpenSSH are weird. Essentially it checks whether a file is either located in a subdirectory of your user home, e.g. `C:\Users\...\**` or the file permissions are set to only allow the current user. Sadly, OpenSSH does not allow you to overwrite that behavior, so I can't disable it.

Right now, it is not possible to switch the type of ssh client to use because others like tabby or putty have a different interface that is not supported right now. It is possible to change the terminal to open the connection in, but not the ssh client itself.

I hope to somehow implement a workaround for this problem soon somehow. But right now there are sadly not a lot of options other than maybe copying the key file into a user directory like `C:\Users\<User>\.ssh` and using it from there. This problem annoyed me as well with OpenSSH, I honestly don't understand why they do not give uses the option to disable that behavior.

**Comment by 001oc** [comment]
@crschnick thanks for the reply. I feared you answer will be that way. As usual, windows clients suck where ever they find a stupid oppurtunity - sometimes I have to use then anyway. I will try your suggestion, thanks.

**Comment by 001oc** [comment]
solved

**Comment by crschnick** [comment]
If you want, you can try whether the latest PTB can fix your original issue: https://github.com/xpipe-io/xpipe-ptb. I added an option to automatically adapt file permissions when OpenSSH complains. However I'm not entirely sure whether that will work for everyone as Windows permissions are weird.

**Comment by 001oc** [comment]
Thanks alot, I will give it a try. But I fear the same as you as I don´t believe that Windows will be cooperative concerning its permission bullshit. As my "problem" is solved in general with the solution you proposed before the latest PTB, I think I will stay with it at the very end - as it works as designed and will not have fight against the rediculous windos permission system.

**Comment by crschnick** [comment]
I just implemented an option to run essentially this: https://superuser.com/a/1329702 when OpenSSH throws in error if the user chooses too.

**Comment by crschnick** [comment]
I guess this can be closed now as xpipe now shows the user possible options on how to fix the problem, even when the manual permissions change does not work.
