### ISSUE TITLE
Feature Request: Settings Synchronization Function

### ISSUE THREAD

**Issue by MagnusHL** [xpipe-io/xpipe#139]
Hi,

I'd like to propose a feature for settings synchronization. This function should allow users to sync their settings either through a designated location in a synchronized directory or via a dedicated cloud sync function. This feature would greatly enhance user experience, especially for those who use the application across multiple devices or environments.

Key Aspects:

Location-based Sync: Users can specify a folder (e.g., in Dropbox, Google Drive) where the application settings file is stored. The app would automatically sync settings to and from this location.
Cloud Sync Function: Alternatively, an in-built cloud synchronization feature would allow users to sync their settings directly through the application, without the need for external services.
This feature would ensure a seamless experience across different devices and improve efficiency and convenience.

Looking forward to your thoughts on this.

Best regards,
Magnus

**Comment by crschnick** [comment]
Are we talking about connection synchronization or actual settings? I.e. do you want to have access to your connections on multiple systems or your settings such as default terminal configuration?

For the connection synchronization, there already is the git vault functionality which you can find in the settings menu under `Vault`. The actual settings are not shared via that though, mainly because they contain platform specific information. The connection data however can be shared cross platform.

**Comment by MagnusHL** [comment]
Great, thank you!
