### ISSUE TITLE
How do I add a dumb terminal launcher

### ISSUE THREAD

**Issue by nzsambo** [xpipe-io/xpipe#144]
I am loving xpipe, it's a game changer.

I have a few Mikrotik routers that would be handy to launch via xpipe. When I add a new SSH connection, it tries to detect the shell and fails. Is it possible to add these purely as a way to launch the terminal?

```
Process did not start up properly and had to be killed:
Unable to determine POSIX shell type
```

Cheers!

**Comment by crschnick** [comment]
That will be added in the future update, I would have to rework some parts to work without known shell type. This is kind of related to #94 . The problem is that even with dumb shells we somehow need to verify whether everything is working as expected and the shell started up, so there probably needs to be some specific code for cisco, mikrotik, etc. devices

**Comment by crschnick** [comment]
Alright, the shell handling has been reworked to allow for dumb shell connections in 1.8 and is currently in testing at https://github.com/xpipe-io/xpipe-ptb. To properly make this work for your case, I would need to know what a mikrotik router prints upon connection so that I can identify that. If I can identify a system, it is now trivial to add support for it as a dumb shell.

**Comment by nzsambo** [comment]
Good stuff! Hope this helps

#### v7

```




  MMM      MMM       KKK                          TTTTTTTTTTT      KKK
  MMMM    MMMM       KKK                          TTTTTTTTTTT      KKK
  MMM MMMM MMM  III  KKK  KKK  RRRRRR     OOOOOO      TTT     III  KKK  KKK
  MMM  MM  MMM  III  KKKKK     RRR  RRR  OOO  OOO     TTT     III  KKKKK
  MMM      MMM  III  KKK KKK   RRRRRR    OOO  OOO     TTT     III  KKK KKK
  MMM      MMM  III  KKK  KKK  RRR  RRR   OOOOOO      TTT     III  KKK  KKK

  MikroTik RouterOS 7.12.1 (c) 1999-2023       https://www.mikrotik.com/

Press F1 for help


[admin@router1] >
```


#### v6

```






  MMM      MMM       KKK                          TTTTTTTTTTT      KKK
  MMMM    MMMM       KKK                          TTTTTTTTTTT      KKK
  MMM MMMM MMM  III  KKK  KKK  RRRRRR     OOOOOO      TTT     III  KKK  KKK
  MMM  MM  MMM  III  KKKKK     RRR  RRR  OOO  OOO     TTT     III  KKKKK
  MMM      MMM  III  KKK KKK   RRRRRR    OOO  OOO     TTT     III  KKK KKK
  MMM      MMM  III  KKK  KKK  RRR  RRR   OOOOOO      TTT     III  KKK  KKK

  MikroTik RouterOS 6.47.9 (c) 1999-2020       http://www.mikrotik.com/

[?]             Gives the list of available commands
command [?]     Gives help on the command and list of arguments

[Tab]           Completes the command/word. If the input is ambiguous,
                a second [Tab] gives possible options

/               Move up to base level
..              Move up one level
/command        Use command at the base level

[admin@router1] >
```

**Comment by crschnick** [comment]
Thanks for that! I guess looking for `MikroTik RouterOS` should be enough? Unless they are other variants than `RouterOS`, maybe we can also just look for the URL `http://www.mikrotik.com/`.

**Comment by nzsambo** [comment]
I think it's safe to use Mikrotik RouterOS

**Comment by crschnick** [comment]
Alright, can you try whether https://github.com/xpipe-io/xpipe-ptb/releases/tag/8.0-9 works for you?

**Comment by nzsambo** [comment]
It's not detecting the shell

```
Process did not start up properly and had to be killed:
Unable to determine POSIX shell type
```

Is your search string / regex case sensitive? *MikroTik RouterOS* with capital T ? 

I just googled this... here's a hosted demo from mikrotik....  `ssh admin@demo.mt.lv`. There's no password, and it will prompt you to change it at first launch.

**Comment by crschnick** [comment]
Thanks for the demo link, that helped.

The root cause was that the shell does not print any welcome screen when being run without a tty with the SSH -T switch. I have adapted the detection to instead look for basic error messages when trying to echo something. You can try this in https://github.com/xpipe-io/xpipe-ptb/releases/tag/8.0-10

Note that this build comes with the preview plan integration, so if everything succeeds it will ask you to use it as a preview. Just let me know whether it gets detected now.

**Comment by crschnick** [comment]
Alright this is now released and should work for you.
