### ISSUE TITLE
file manager improvement

### ISSUE THREAD

**Issue by brianshen0522** [xpipe-io/xpipe#152]
I recomend to add a process bar when operating files, ex upload download
![image](https://github.com/xpipe-io/xpipe/assets/44171953/5ab05c6b-e267-4a7a-8d09-f739dacb08ed)

**Comment by crschnick** [comment]
Yes, that is already planned. I will see what I can do about that

**Comment by crschnick** [comment]
The drag and drop to local is realized through the transfer pane in the bottom left corner. It takes two steps to have the files available locally instead of one but allows for a much more robust file handling.

For the other way around, you should be able to drag local files into the remote system directly already.

**Comment by crschnick** [comment]
A progress indicator has now been added to the status bar in the latest release
