### ISSUE TITLE
VS Codium as custom editor

### ISSUE THREAD

**Issue by MariMightyMedia** [xpipe-io/xpipe#179]
For the "default program" at the setting "Editor" I entered custom and entered the following command_

`vsc $FILE
`

which typically starts a file in vs codium.

But some reason it doesn't work when I click "test" and also isn't working when I'm opening a file via XPipe. ("edit with custom")

Would be nice if that could be fixed.

One thing that does somehow work is, when I have VsCodium as a default app on my Mac for .txt files for example and I'm using the "open with default application" option.

**Comment by crschnick** [comment]
Hmm from you description it should work, especially if `vsc <file>` opens the editor otherwise when you type that into the terminal. Is there any error shown?

Because xpipe also just runs the command in your default shell.

If nothing like that works, something like `open -a VSCodium.app --args $FILE` should also work. I don't node exact .app name, but you get the idea.

**Comment by MariMightyMedia** [comment]
Hey thank you very much! We have made a step forward.
With `open -a VSCodium.app --args $FILE` at least the "Test" button is working but somehow when I'm using the "edit with custom" option at any file in XPipe it doesn't open the file even though it opens up VS Codium.

My guess would be, that the problem is related to '$FILE' with MacOS, because it opens up VS Codium but not the actual file.

**Comment by crschnick** [comment]
Does the command `open -a VSCodium.app --args <file>` work if you manually run it with an existing file in your terminal?

**Comment by MariMightyMedia** [comment]
Nope

**Comment by crschnick** [comment]
vscodium support will be added in the next release

**Comment by MariMightyMedia** [comment]
All right thank you very much!!
