### ISSUE TITLE
can't connect to the bastion

### ISSUE THREAD

**Issue by judzk** [xpipe-io/xpipe#213]
Hi, at work we are deploying the bastion "https://github.com/ovh/the-bastion"
But I can't connect with it with xpipe.
After setting my connection, i opened it and it opened a windows with "launching", et then timeout

If I use the insight command directly on my powershell ( i'm in windows 11 ), it works without issues

Here is the log, but not relevant i guess

`
The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
~ [#] No command specified, entering interactive mode by default
`

**Comment by crschnick** [comment]
I have to set that up myself and see what is happening there, so I will get back to you.

If you only want to use that bastion as a SSH jump server, that should still work by creating a custom SSH connection with the `ProxyJump` value.

**Comment by judzk** [comment]
Thank for your reply, it's not urgent, don't worry ;)
For now, i can't connect to the bastion in direct connection via HAproxy, i will try in direct connection

**Comment by crschnick** [comment]
So I set this up myself, and the reason is that they obviously use their own kind of login shell to allow for these custom commands. XPipe expects a normal command shell, for example bash, so it gets confused.

I added support for the ovh bastion in 8.5, but since this required me to write a separate implementation just for this type of bastion, and it is primarily used in a commercial context, I added the support to the professional edition. If you want, you can try out whether it works for you via the professional preview option. It should give you the option to freely use the ovh bastion support for a couple of weeks without having to buy anything.

**Comment by judzk** [comment]
Thank for looking into it. But we use it on professional context, not commercial. And since we don't have any money for buying software when another do it for free. Like putty. I can't buy it
But thank you for your time

**Comment by crschnick** [comment]
Hmm I see. If you want, you can elaborate a bit on how you use it, that way I get a better idea of the context. Because it is not my intention to charge for noncommercial use, I was just under the impression that this would be used almost exclusively for commercial usage. So maybe I can find a better solution for this

**Comment by judzk** [comment]
Strictly security, we have 15/20 server at work, but some people need to access it from a remote place or work remotely.
Instead of opening several server in ssh to the web. We only open the bastion.
Also we use bastion to give easily access to some server to some people.
At work in a little university, so no commercial business.

**Comment by crschnick** [comment]
Ah I see. Since I'm currently reworking the website at https://xpipe.io/ and the pricing model, I think it would be a good time to also think about free education licenses as you have with many other tools. Let me work on this and I will get back to you soon.

**Comment by judzk** [comment]
I think it's a good idea, I will try tomorrow the new features.

**Comment by crschnick** [comment]
Alright, I created a special education license system, will probably be released tomorrow in 8.6. You can send an email to hello@xpipe.io with your edu email and I will send you the license link once everything is ready.
