### ISSUE TITLE
Bug Copying files

### ISSUE THREAD

**Issue by meska** [xpipe-io/xpipe#262]
In one of my hosts I have this strange behaviour:

https://github.com/xpipe-io/xpipe/assets/276923/997f16e5-a70a-41c1-ba80-3df867c1f9e0

**Comment by crschnick** [comment]
Does that also happen if you copy only one file like that?

I will have to pull out my mac to test this

**Comment by crschnick** [comment]
This will be fixed in the next release, it seems like macos handles the mime types differently when dragging files.

The intended way of downloading files is to first put them into the transfer view on the bottom left, press download there, and then drag the files to your local desktop. It should not be possible to drag them directly into the local desktop but due to this bug, I can see how it can be confusing.

**Comment by tacaly** [comment]
Fixed in release.
