### ISSUE TITLE
[Feature Request] Proxmox Tweaks 

### ISSUE THREAD

**Issue by valdearg** [xpipe-io/xpipe#313]
Hello!

First, absolutely love xpipe, the steady improvements to this has made it great to use and exactly what I've been wanting for a while.

Was wondering if I could make a couple of suggestions on the Proxmox integration:

1. Display difference between "running" and "not reachable" VMs
![image](https://github.com/user-attachments/assets/d66cadf3-b088-4a95-9394-c1604d80d9e9)
I feel like the red tex for running VMs should be a more "positive" colour such as the green online colour/icon used for the services. 

2. "Not reachable" could ideally be "stopped". This generally matches the language used by the Proxmox website. 

3. Templates appear in the VM list, as a standard VM (the VM 9000/7000 in the above screenshot). I'm wondering if it might be best to filter these out. 

4. Connections to the Proxmox VMs. I'm wondering if for the SSH there might be a method of using a key based auth here also, currently it just has the user password option.
![652-782-max](https://github.com/user-attachments/assets/e53e95a5-bb91-41ca-a761-0703774d8cea)

5. Set OS type or connection type. For example I host a variety of OS types on Proxmox including Linux/Windows/macOS. It would be great to be able to select the connection type, RDP/SSH/etc. It might be possible to proxy the console session too, e.g. spice desktop?

**Comment by crschnick** [comment]
1. The red text is only to indicate that a connection has not been configured yet and cannot be used right now. As soon as you fill in the missing information, it's listed as normal. 
2. That can be possibly implemented. Right now this is just a catch all because xpipe doesn't do a state detection before connecting. If for whatever reason a connection fails, it will just list it as not reachable
3. Is there a way to detect that when running `qm list` when it is a template?
4. That can be added, I was just under the assumption that most people don't set up their individual vms other than the default authentication. Right now you can still connect to it if you manually add a ssh connection as a workaround
5. The OS type should ideally be already automatically detected. For other connection types, you can use an individual proxmox connection in xpipe to add other child connections such as RDP if you want. I have not looked into SPICE yet, I can try to find out what is going on there

**Comment by crschnick** [comment]
I reworked the state display for 2.

You can try it out at https://github.com/xpipe-io/xpipe-ptb and see whether it is now better for you

**Comment by valdearg** [comment]
Thanks! That does look better on 2!

Sadly it looks like qm list doesn't show if an item is a template, so may not be possible. 

I was just taking a look into how Proxmox do it and it looks like the API does display this info, e.g.

```
        {
            "uptime": 0,
            "maxmem": 2147483648,
            "template": 1,
            "name": "Ubuntu-Server-23.04",
            "cpu": 0,
            "maxdisk": 3758096384,
            "diskread": 0,
            "disk": 0,
            "diskwrite": 0,
            "netout": 0,
            "netin": 0,
            "serial": 1,
            "cpus": 1,
            "vmid": 8000,
            "status": "stopped",
            "mem": 0
        },
```

But probably a pain to implement vs just the qm list so not to worry about.

**Comment by crschnick** [comment]
Or is there a specific naming pattern for templates like in your case? Or can the names be completely random, I haven't really used templates

**Comment by crschnick** [comment]
The status output has been improved a bit and there's now a toggle to only show running VMs/containers. I think this will get rid of the template issues a bit, at least they are not shown always now

**Comment by crschnick** [comment]
Key-based connections are now possible in XPipe 12. There have also been various other improvements to the proxmox display, so I think we can close this
