### ISSUE TITLE
VNC without SSH Tunnel

### ISSUE THREAD

**Issue by scottgrobinson** [xpipe-io/xpipe#321]
Hello,

Is there any way to connect to a VNC server without an SSH tunnel, similar to how the RDP functionality has been implemented?

**Comment by crschnick** [comment]
Not right now, mainly because xpipe does not implement advanced encryption measures for VNC. The SSH tunnel guarantees that all traffic is encrypted. Without that, it would be insecure.

Do you have the system that is not reachable via SSH?

**Comment by scottgrobinson** [comment]
Thanks for the info. Just trying to migrate from RoyalTS as I've switched to using Windows & Ubuntu 50% of the time rather than Windows 100% of the time. 

I've got a number of windows clients with VNC setup behind a secure VPN so the insecurity aspect isn't relevant for those.

**Comment by crschnick** [comment]
I guess in these cases it would be secure, but xpipe doesn't know that for sure. Also implementing all the advanced encryption extensions for VNC would be a lot of work. With SSH it's just much easier.

Is this a problem for you, i.e. are you unable to connect via SSH?

**Comment by crschnick** [comment]
Also to add to this, having an active shell connection in the background with SSH allows xpipe to realize a few additional features. E.g. to support dropping files directly into the VNC session. That would not be possible without SSH.

**Comment by scottgrobinson** [comment]
Appreciate the quick replies - I'll give things a try in the week and see what's feasible. A number of the windows machines don't have SSH and I couldn't seem to get them running on there but will have a play and see what happens.

**Comment by crschnick** [comment]
There are several known issues with OpenSSH on Windows. Most of the time the solution is to manually install the latest OpenSSH server, e.g. as in https://github.com/xpipe-io/xpipe/issues/257#issuecomment-2096945084

**Comment by davidfreina** [comment]
I would be interested in having this functionality as well.
I'm trying to connect to a PLC that is running a VNC server.
However, it is not possible to connect to the with SSH because it is locked by the vendor.

Maybe with regard to the security aspect it would be a possibility to only allow "direct" VNC connections in local subnets.
That would at least provide some assurance to XPipe that the connection isn't fully unencrypted (VPN) or at least in a local network, where security wouldn't be such a big factor.

For now I am using a bit of a workaround by utilizing a script which opens RealVNC's VNC viewer with a saved config file.
While that works it would be great to have a one-click solution for this.

**Comment by crschnick** [comment]
I see your point. I would have to think about how to solve this the best way. That would probably require adding a new connection type for direct VNC connections

**Comment by crschnick** [comment]
In 11.2, XPipe now supports a limited amount of encrypted transfer methods. It makes sense to enable this now. You can now create direct VNC connections that do not require a tunnel.
