### ISSUE TITLE
Concern about closed source plugins

### ISSUE THREAD

**Issue by hahn-kev** [xpipe-io/xpipe#85]
Hi, I'm enjoying using this tool, however I'm worried about some plugins that are included in the released builds that are not included in this repo. I noticed this with the k8s functionality, there's no code in this repo dedicated to those features.

You mention this in the [development document](https://github.com/xpipe-io/xpipe/blob/master/DEVELOPMENT.md#open-source-model) however this is something that would be important for making a decision to use this product and I would expect it to be flagged in the main README of the repo. In the development document you highlight tests and such that aren't public and that's fine, but I would like to be able to review any of the code that ends up in the application that I download and install.

**Comment by crschnick** [comment]
Yeah I see your point, I should highlight that more. So I will update the readmes.

I already talked about the open source model in another thread, so you can take a look at it: https://github.com/xpipe-io/xpipe/issues/57#issuecomment-1646665216. Essentially, my initial plan was to only keep the internal shell handling logic private, as that is the differentiating factor. However, as it turned out during development, there was a need for close coupling and subclassing of the shell control classes, which required more and more classes to be in the same private module. I hope to solve this issue sometime, maybe through smart splitting or selective filtering of the committed files.

**Comment by crschnick** [comment]
How does this look for you: https://github.com/xpipe-io/xpipe#open-source-model ?

**Comment by crschnick** [comment]
At the end of the day you have to decide for yourself whether this is acceptable for you when using xpipe. I will close this for now, but if you think that the notice can be improved somewhat, we can reopen this

**Comment by hahn-kev** [comment]
Thank you, I think that makes sense, I appreciate that you're open to feedback.
